[project]
name = "46-multimodal-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ollama-haystack>=6.8.0",
    "pillow>=12.3.0",
    "pypdf>=6.14.2",
    "pypdfium2>=5.12.1",
    "sentence-transformers-haystack>=0.1.1",
]
