[project]
name = "39-embedding-metadata-for-improved-retrieval"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "haystack-ai>=3.0.0",
    "sentence-transformers-haystack>=0.1.1",
    "wikipedia>=1.4.0",
]
