[project]
name = "cross-encoder-reranker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "faiss-cpu>=1.14.3",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "sentence-transformers>=5.6.1",
]
